image: debian/stable
packages:
  - golang
  - curl
secrets:
  - a6fb7811-e817-4766-ab9f-a7e6751902e2
sources:
  - https://git.sr.ht/~mjorgensen/jphotos
  - https://git.sr.ht/~sircmpwn/annotatego
triggers:
  - action: email
    condition: always
    to: notify@jrgnsn.net
tasks:
  - is-master: |
      cd jphotos
      if [ "$(git rev-parse master)" != "$(git rev-parse HEAD)" ]; then
        complete-build;
      fi
  - build: |
      cd jphotos
      go build ./cmd/jphotos-server
  - annotatego: |
      cd annotatego
      go build
      sudo cp annotatego /usr/bin/
  - annotate: |
      cd jphotos
      annotatego -v git.sr.ht/~mjorgensen/jphotos... >annotations.json
      ~/upload-annotations annotations.json mjorgensen jphotos
